'use strict';

/**
 * The question bank for the daily Bible quiz. Each entry has the question and four options in
 * English and Telugu, and the index of the correct option (the same in both languages).
 * Three questions a day are drawn in order by date, so the bank cycles every 20 days; add more
 * entries at the end and the cycle simply grows.
 */
const QUESTIONS = [
  { id: 'q1', answer: 1, en: { q: 'Who built the ark?', o: ['Moses', 'Noah', 'Abraham', 'David'] }, te: { q: 'ఓడను ఎవరు నిర్మించారు?', o: ['మోషే', 'నోవహు', 'అబ్రాహాము', 'దావీదు'] } },
  { id: 'q2', answer: 2, en: { q: 'How many days did God take to create the world?', o: ['3', '5', '6', '7'] }, te: { q: 'దేవుడు లోకాన్ని ఎన్ని రోజుల్లో సృష్టించాడు?', o: ['3', '5', '6', '7'] } },
  { id: 'q3', answer: 0, en: { q: 'Who was the first man God created?', o: ['Adam', 'Abel', 'Cain', 'Seth'] }, te: { q: 'దేవుడు సృష్టించిన మొదటి మనిషి ఎవరు?', o: ['ఆదాము', 'హేబెలు', 'కయీను', 'షేతు'] } },
  { id: 'q4', answer: 3, en: { q: 'Who led the Israelites out of Egypt?', o: ['Joshua', 'Aaron', 'Joseph', 'Moses'] }, te: { q: 'ఇశ్రాయేలీయులను ఐగుప్తు నుండి బయటకు నడిపించినది ఎవరు?', o: ['యెహోషువ', 'అహరోను', 'యోసేపు', 'మోషే'] } },
  { id: 'q5', answer: 1, en: { q: 'How many books are in the Bible?', o: ['39', '66', '27', '73'] }, te: { q: 'బైబిల్‌లో ఎన్ని పుస్తకాలు ఉన్నాయి?', o: ['39', '66', '27', '73'] } },
  { id: 'q6', answer: 2, en: { q: 'Who killed Goliath?', o: ['Saul', 'Samson', 'David', 'Jonathan'] }, te: { q: 'గొల్యాతును చంపినది ఎవరు?', o: ['సౌలు', 'సమ్సోను', 'దావీదు', 'యోనాతాను'] } },
  { id: 'q7', answer: 0, en: { q: 'In which town was Jesus born?', o: ['Bethlehem', 'Nazareth', 'Jerusalem', 'Capernaum'] }, te: { q: 'యేసు ఏ ఊరిలో జన్మించాడు?', o: ['బేత్లెహేము', 'నజరేతు', 'యెరూషలేము', 'కపెర్నహూము'] } },
  { id: 'q8', answer: 3, en: { q: 'How many disciples did Jesus choose?', o: ['7', '10', '11', '12'] }, te: { q: 'యేసు ఎంతమంది శిష్యులను ఎన్నుకున్నాడు?', o: ['7', '10', '11', '12'] } },
  { id: 'q9', answer: 1, en: { q: 'Who was swallowed by a great fish?', o: ['Elijah', 'Jonah', 'Daniel', 'Peter'] }, te: { q: 'పెద్ద చేప ఎవరిని మింగింది?', o: ['ఏలీయా', 'యోనా', 'దానియేలు', 'పేతురు'] } },
  { id: 'q10', answer: 2, en: { q: 'Who was thrown into the lions’ den?', o: ['Joseph', 'Jeremiah', 'Daniel', 'Elisha'] }, te: { q: 'సింహాల గుహలో ఎవరిని పడవేశారు?', o: ['యోసేపు', 'యిర్మీయా', 'దానియేలు', 'ఎలీషా'] } },
  { id: 'q11', answer: 0, en: { q: 'What is the first book of the Bible?', o: ['Genesis', 'Exodus', 'Matthew', 'Psalms'] }, te: { q: 'బైబిల్‌లోని మొదటి పుస్తకం ఏది?', o: ['ఆదికాండము', 'నిర్గమకాండము', 'మత్తయి', 'కీర్తనలు'] } },
  { id: 'q12', answer: 3, en: { q: 'What is the last book of the Bible?', o: ['Jude', 'Acts', 'Hebrews', 'Revelation'] }, te: { q: 'బైబిల్‌లోని చివరి పుస్తకం ఏది?', o: ['యూదా', 'అపొస్తలుల కార్యములు', 'హెబ్రీయులకు', 'ప్రకటన'] } },
  { id: 'q13', answer: 1, en: { q: 'Who betrayed Jesus for thirty pieces of silver?', o: ['Peter', 'Judas Iscariot', 'Thomas', 'Pilate'] }, te: { q: 'ముప్పై వెండి నాణేలకు యేసును అప్పగించినది ఎవరు?', o: ['పేతురు', 'ఇస్కరియోతు యూదా', 'తోమా', 'పిలాతు'] } },
  { id: 'q14', answer: 2, en: { q: 'Who denied Jesus three times?', o: ['John', 'James', 'Peter', 'Andrew'] }, te: { q: 'యేసును మూడుసార్లు ఎరుగనని చెప్పినది ఎవరు?', o: ['యోహాను', 'యాకోబు', 'పేతురు', 'అంద్రెయ'] } },
  { id: 'q15', answer: 0, en: { q: 'Who was the mother of Jesus?', o: ['Mary', 'Martha', 'Elizabeth', 'Ruth'] }, te: { q: 'యేసు తల్లి ఎవరు?', o: ['మరియ', 'మార్త', 'ఎలీసబెతు', 'రూతు'] } },
  { id: 'q16', answer: 3, en: { q: 'Who baptised Jesus?', o: ['Peter', 'Paul', 'Elijah', 'John the Baptist'] }, te: { q: 'యేసుకు బాప్తిస్మం ఇచ్చినది ఎవరు?', o: ['పేతురు', 'పౌలు', 'ఏలీయా', 'బాప్తిస్మమిచ్చు యోహాను'] } },
  { id: 'q17', answer: 1, en: { q: 'How many days was Jesus in the tomb?', o: ['1', '3', '7', '40'] }, te: { q: 'యేసు సమాధిలో ఎన్ని రోజులు ఉన్నాడు?', o: ['1', '3', '7', '40'] } },
  { id: 'q18', answer: 2, en: { q: 'Who wrote most of the Psalms?', o: ['Solomon', 'Moses', 'David', 'Asaph'] }, te: { q: 'కీర్తనలలో అధిక భాగం రాసినది ఎవరు?', o: ['సొలొమోను', 'మోషే', 'దావీదు', 'ఆసాపు'] } },
  { id: 'q19', answer: 0, en: { q: 'Which king asked God for wisdom?', o: ['Solomon', 'Saul', 'Ahab', 'Hezekiah'] }, te: { q: 'దేవుని దగ్గర జ్ఞానం అడిగిన రాజు ఎవరు?', o: ['సొలొమోను', 'సౌలు', 'అహాబు', 'హిజ్కియా'] } },
  { id: 'q20', answer: 3, en: { q: 'Who was sold by his brothers into Egypt?', o: ['Benjamin', 'Reuben', 'Judah', 'Joseph'] }, te: { q: 'సోదరులు ఐగుప్తుకు అమ్మివేసినది ఎవరిని?', o: ['బెన్యామీను', 'రూబేను', 'యూదా', 'యోసేపు'] } },
  { id: 'q21', answer: 1, en: { q: 'Who was the strongest man in the Bible?', o: ['Goliath', 'Samson', 'Saul', 'Gideon'] }, te: { q: 'బైబిల్‌లో అత్యంత బలవంతుడు ఎవరు?', o: ['గొల్యాతు', 'సమ్సోను', 'సౌలు', 'గిద్యోను'] } },
  { id: 'q22', answer: 2, en: { q: 'Which woman said, “Where you go I will go”?', o: ['Esther', 'Naomi', 'Ruth', 'Hannah'] }, te: { q: '“నీవు వెళ్లు చోటికే నేను వస్తాను” అని చెప్పిన స్త్రీ ఎవరు?', o: ['ఎస్తేరు', 'నయోమి', 'రూతు', 'హన్నా'] } },
  { id: 'q23', answer: 0, en: { q: 'Which queen saved her people from Haman’s plot?', o: ['Esther', 'Sheba', 'Jezebel', 'Vashti'] }, te: { q: 'హామాను కుట్ర నుండి తన ప్రజలను కాపాడిన రాణి ఎవరు?', o: ['ఎస్తేరు', 'షేబ', 'యెజెబెలు', 'వష్తి'] } },
  { id: 'q24', answer: 3, en: { q: 'Who was the father of Isaac?', o: ['Jacob', 'Noah', 'Lot', 'Abraham'] }, te: { q: 'ఇస్సాకు తండ్రి ఎవరు?', o: ['యాకోబు', 'నోవహు', 'లోతు', 'అబ్రాహాము'] } },
  { id: 'q25', answer: 1, en: { q: 'What did God give Moses on Mount Sinai?', o: ['A crown', 'The Ten Commandments', 'A staff', 'Manna'] }, te: { q: 'సీనాయి కొండపై దేవుడు మోషేకు ఏమి ఇచ్చాడు?', o: ['కిరీటం', 'పది ఆజ్ఞలు', 'కర్ర', 'మన్నా'] } },
  { id: 'q26', answer: 2, en: { q: 'What food did God send in the wilderness?', o: ['Bread from Egypt', 'Figs', 'Manna', 'Honey cakes'] }, te: { q: 'అరణ్యంలో దేవుడు పంపిన ఆహారం ఏది?', o: ['ఐగుప్తు రొట్టె', 'అంజూరపు పండ్లు', 'మన్నా', 'తేనె రొట్టెలు'] } },
  { id: 'q27', answer: 0, en: { q: 'Which sea parted for the Israelites?', o: ['Red Sea', 'Dead Sea', 'Sea of Galilee', 'Mediterranean Sea'] }, te: { q: 'ఇశ్రాయేలీయుల కోసం విడిపోయిన సముద్రం ఏది?', o: ['ఎర్ర సముద్రం', 'మృత సముద్రం', 'గలిలయ సముద్రం', 'మధ్యధరా సముద్రం'] } },
  { id: 'q28', answer: 3, en: { q: 'Whose walls fell after the people marched around them?', o: ['Babylon', 'Nineveh', 'Jerusalem', 'Jericho'] }, te: { q: 'ప్రజలు చుట్టూ తిరిగిన తర్వాత ఏ పట్టణ గోడలు కూలిపోయాయి?', o: ['బబులోను', 'నీనెవె', 'యెరూషలేము', 'యెరికో'] } },
  { id: 'q29', answer: 1, en: { q: 'Who was the wife of Abraham?', o: ['Rebekah', 'Sarah', 'Rachel', 'Leah'] }, te: { q: 'అబ్రాహాము భార్య ఎవరు?', o: ['రిబ్కా', 'శారా', 'రాహేలు', 'లేయా'] } },
  { id: 'q30', answer: 2, en: { q: 'Who interpreted Pharaoh’s dreams?', o: ['Daniel', 'Moses', 'Joseph', 'Aaron'] }, te: { q: 'ఫరో కలలకు అర్థం చెప్పినది ఎవరు?', o: ['దానియేలు', 'మోషే', 'యోసేపు', 'అహరోను'] } },
  { id: 'q31', answer: 0, en: { q: 'Which prophet was taken to heaven in a whirlwind?', o: ['Elijah', 'Elisha', 'Isaiah', 'Enoch'] }, te: { q: 'సుడిగాలిలో పరలోకానికి తీసుకుపోబడిన ప్రవక్త ఎవరు?', o: ['ఏలీయా', 'ఎలీషా', 'యెషయా', 'హనోకు'] } },
  { id: 'q32', answer: 3, en: { q: 'What was the first miracle of Jesus?', o: ['Walking on water', 'Feeding 5,000', 'Healing a leper', 'Turning water into wine'] }, te: { q: 'యేసు చేసిన మొదటి అద్భుతం ఏది?', o: ['నీటిపై నడవడం', '5,000 మందికి భోజనం', 'కుష్ఠరోగిని స్వస్థపరచడం', 'నీటిని ద్రాక్షారసంగా మార్చడం'] } },
  { id: 'q33', answer: 1, en: { q: 'With how many loaves did Jesus feed the five thousand?', o: ['2', '5', '7', '12'] }, te: { q: 'యేసు ఐదువేల మందికి ఎన్ని రొట్టెలతో భోజనం పెట్టాడు?', o: ['2', '5', '7', '12'] } },
  { id: 'q34', answer: 2, en: { q: 'Who climbed a tree to see Jesus?', o: ['Nicodemus', 'Bartimaeus', 'Zacchaeus', 'Lazarus'] }, te: { q: 'యేసును చూడటానికి చెట్టు ఎక్కినది ఎవరు?', o: ['నీకొదేము', 'బర్తిమయి', 'జక్కయ్య', 'లాజరు'] } },
  { id: 'q35', answer: 0, en: { q: 'Whom did Jesus raise from the dead after four days?', o: ['Lazarus', 'Jairus’ daughter', 'The widow’s son', 'Tabitha'] }, te: { q: 'నాలుగు రోజుల తర్వాత యేసు ఎవరిని మృతులలో నుండి లేపాడు?', o: ['లాజరు', 'యాయీరు కుమార్తె', 'విధవరాలి కుమారుడు', 'తబిత'] } },
  { id: 'q36', answer: 3, en: { q: 'Which parable tells of a son who came home to his father?', o: ['The Good Samaritan', 'The Sower', 'The Lost Sheep', 'The Prodigal Son'] }, te: { q: 'తండ్రి దగ్గరకు తిరిగి వచ్చిన కుమారుని గురించిన ఉపమానం ఏది?', o: ['మంచి సమరయుడు', 'విత్తువాడు', 'తప్పిపోయిన గొర్రె', 'తప్పిపోయిన కుమారుడు'] } },
  { id: 'q37', answer: 1, en: { q: 'Who helped the wounded man on the road to Jericho?', o: ['A priest', 'A Samaritan', 'A Levite', 'A soldier'] }, te: { q: 'యెరికో దారిలో గాయపడిన వ్యక్తికి సహాయం చేసినది ఎవరు?', o: ['యాజకుడు', 'సమరయుడు', 'లేవీయుడు', 'సైనికుడు'] } },
  { id: 'q38', answer: 2, en: { q: 'Which apostle was a tax collector?', o: ['Peter', 'John', 'Matthew', 'Philip'] }, te: { q: 'సుంకరిగా ఉన్న అపొస్తలుడు ఎవరు?', o: ['పేతురు', 'యోహాను', 'మత్తయి', 'ఫిలిప్పు'] } },
  { id: 'q39', answer: 0, en: { q: 'On which road did Saul meet Jesus?', o: ['Damascus', 'Emmaus', 'Jericho', 'Bethany'] }, te: { q: 'సౌలు యేసును ఏ మార్గంలో కలుసుకున్నాడు?', o: ['దమస్కు', 'ఎమ్మాయు', 'యెరికో', 'బేతనియ'] } },
  { id: 'q40', answer: 3, en: { q: 'What is the shortest verse in the Bible?', o: ['Rejoice always', 'Pray continually', 'God is love', 'Jesus wept'] }, te: { q: 'బైబిల్‌లోని అతి చిన్న వచనం ఏది?', o: ['ఎల్లప్పుడు సంతోషించండి', 'ఎడతెగక ప్రార్థించండి', 'దేవుడు ప్రేమ', 'యేసు కన్నీళ్లు విడిచెను'] } },
  { id: 'q41', answer: 1, en: { q: 'Which is the longest book in the Bible?', o: ['Genesis', 'Psalms', 'Isaiah', 'Jeremiah'] }, te: { q: 'బైబిల్‌లోని అతి పెద్ద పుస్తకం ఏది?', o: ['ఆదికాండము', 'కీర్తనలు', 'యెషయా', 'యిర్మీయా'] } },
  { id: 'q42', answer: 2, en: { q: 'How many years did the Israelites wander in the wilderness?', o: ['7', '12', '40', '70'] }, te: { q: 'ఇశ్రాయేలీయులు అరణ్యంలో ఎన్ని సంవత్సరాలు తిరిగారు?', o: ['7', '12', '40', '70'] } },
  { id: 'q43', answer: 0, en: { q: 'Who was the first king of Israel?', o: ['Saul', 'David', 'Solomon', 'Samuel'] }, te: { q: 'ఇశ్రాయేలు మొదటి రాజు ఎవరు?', o: ['సౌలు', 'దావీదు', 'సొలొమోను', 'సమూయేలు'] } },
  { id: 'q44', answer: 3, en: { q: 'Who was the mother of Samuel?', o: ['Rachel', 'Deborah', 'Miriam', 'Hannah'] }, te: { q: 'సమూయేలు తల్లి ఎవరు?', o: ['రాహేలు', 'దెబోరా', 'మిర్యాము', 'హన్నా'] } },
  { id: 'q45', answer: 1, en: { q: 'Which prophet confronted the prophets of Baal on Mount Carmel?', o: ['Elisha', 'Elijah', 'Amos', 'Micah'] }, te: { q: 'కర్మెలు కొండపై బయలు ప్రవక్తలను ఎదిరించిన ప్రవక్త ఎవరు?', o: ['ఎలీషా', 'ఏలీయా', 'ఆమోసు', 'మీకా'] } },
  { id: 'q46', answer: 2, en: { q: 'Who wrote the book of Revelation?', o: ['Paul', 'Peter', 'John', 'Luke'] }, te: { q: 'ప్రకటన గ్రంథం రాసినది ఎవరు?', o: ['పౌలు', 'పేతురు', 'యోహాను', 'లూకా'] } },
  { id: 'q47', answer: 0, en: { q: 'Who was a doctor among the Gospel writers?', o: ['Luke', 'Mark', 'Matthew', 'John'] }, te: { q: 'సువార్త రచయితలలో వైద్యుడు ఎవరు?', o: ['లూకా', 'మార్కు', 'మత్తయి', 'యోహాను'] } },
  { id: 'q48', answer: 3, en: { q: 'What fruit of the Spirit is listed first in Galatians 5?', o: ['Peace', 'Patience', 'Joy', 'Love'] }, te: { q: 'గలతీ 5లో ఆత్మ ఫలంలో మొదట చెప్పబడినది ఏది?', o: ['సమాధానం', 'దీర్ఘశాంతం', 'ఆనందం', 'ప్రేమ'] } },
  { id: 'q49', answer: 1, en: { q: 'Where did Jesus give the Sermon on the Mount?', o: ['In the temple', 'On a mountainside', 'By the sea', 'In a synagogue'] }, te: { q: 'యేసు కొండమీది ప్రసంగం ఎక్కడ చేశాడు?', o: ['దేవాలయంలో', 'కొండ మీద', 'సముద్రం దగ్గర', 'సమాజమందిరంలో'] } },
  { id: 'q50', answer: 2, en: { q: 'What did the wise men follow to find Jesus?', o: ['A map', 'An angel', 'A star', 'A river'] }, te: { q: 'యేసును కనుగొనడానికి జ్ఞానులు దేనిని అనుసరించారు?', o: ['పటం', 'దేవదూత', 'నక్షత్రం', 'నది'] } },
  { id: 'q51', answer: 0, en: { q: 'Who was the brother of Moses?', o: ['Aaron', 'Joshua', 'Caleb', 'Hur'] }, te: { q: 'మోషే సోదరుడు ఎవరు?', o: ['అహరోను', 'యెహోషువ', 'కాలేబు', 'హూరు'] } },
  { id: 'q52', answer: 3, en: { q: 'Who was the sister of Moses?', o: ['Deborah', 'Zipporah', 'Jochebed', 'Miriam'] }, te: { q: 'మోషే సోదరి ఎవరు?', o: ['దెబోరా', 'సిప్పోరా', 'యోకెబెదు', 'మిర్యాము'] } },
  { id: 'q53', answer: 1, en: { q: 'Who led Israel into the Promised Land after Moses?', o: ['Caleb', 'Joshua', 'Gideon', 'Samuel'] }, te: { q: 'మోషే తర్వాత ఇశ్రాయేలును వాగ్దాన దేశంలోకి నడిపించినది ఎవరు?', o: ['కాలేబు', 'యెహోషువ', 'గిద్యోను', 'సమూయేలు'] } },
  { id: 'q54', answer: 2, en: { q: 'How many plagues did God send on Egypt?', o: ['5', '7', '10', '12'] }, te: { q: 'దేవుడు ఐగుప్తు మీద ఎన్ని తెగుళ్లు పంపాడు?', o: ['5', '7', '10', '12'] } },
  { id: 'q55', answer: 0, en: { q: 'What sign did God give Noah after the flood?', o: ['A rainbow', 'A dove', 'A star', 'A fire'] }, te: { q: 'జలప్రళయం తర్వాత దేవుడు నోవహుకు ఇచ్చిన గుర్తు ఏది?', o: ['ఇంద్రధనుస్సు', 'పావురం', 'నక్షత్రం', 'అగ్ని'] } },
  { id: 'q56', answer: 3, en: { q: 'Who was the wife of Isaac?', o: ['Leah', 'Rachel', 'Sarah', 'Rebekah'] }, te: { q: 'ఇస్సాకు భార్య ఎవరు?', o: ['లేయా', 'రాహేలు', 'శారా', 'రిబ్కా'] } },
  { id: 'q57', answer: 1, en: { q: 'How many sons did Jacob have?', o: ['7', '12', '10', '14'] }, te: { q: 'యాకోబుకు ఎంతమంది కుమారులు?', o: ['7', '12', '10', '14'] } },
  { id: 'q58', answer: 2, en: { q: 'Who visited Jesus at night to ask about being born again?', o: ['Joseph of Arimathea', 'Zacchaeus', 'Nicodemus', 'Simon'] }, te: { q: 'తిరిగి జన్మించడం గురించి అడగడానికి రాత్రి యేసు దగ్గరకు వచ్చినది ఎవరు?', o: ['అరిమతయియ యోసేపు', 'జక్కయ్య', 'నీకొదేము', 'సీమోను'] } },
  { id: 'q59', answer: 0, en: { q: 'What did Jesus say is the greatest commandment?', o: ['Love the Lord your God', 'Do not steal', 'Honour your parents', 'Keep the Sabbath'] }, te: { q: 'యేసు చెప్పిన గొప్ప ఆజ్ఞ ఏది?', o: ['నీ దేవుడైన ప్రభువును ప్రేమించు', 'దొంగిలించవద్దు', 'తల్లిదండ్రులను ఘనపరచు', 'విశ్రాంతి దినాన్ని ఆచరించు'] } },
  { id: 'q60', answer: 3, en: { q: 'On which day did the Holy Spirit come upon the disciples?', o: ['Passover', 'Sabbath', 'Purim', 'Pentecost'] }, te: { q: 'శిష్యుల మీదకు పరిశుద్ధాత్మ ఏ రోజున దిగివచ్చాడు?', o: ['పస్కా', 'విశ్రాంతి దినం', 'పూరీము', 'పెంతెకొస్తు'] } },
];

module.exports = { QUESTIONS };
